### ISSUE TITLE
Bug on IE

### ISSUE THREAD

**Issue by kimljj** [eXon/videojs-youtube#376] opened 2016-03-30 13:48 UTC
Hi Guys,

I am building moment a video component with videojs (5.8.0) and videojs-youtube (2.0.8). On Chrome and firefox works very well. But on IE 11 the poster doesn't disappear and the video play unvisible, until man double click on it, then we will see the video on fullscreen mode.

Here is also a example I found. https://static.bini.io/cus-videos/ 

Thank your so much for this wonderful plugin

Jinjin

**Comment by gkatsev** [comment] 2016-05-10 19:43
Looks like this is more or less a duplicate of https://github.com/eXon/videojs-youtube/issues/342

**Closed** 2016-05-11 04:41 UTC
