### ISSUE TITLE
Changing source from Youtube to .mp4 video is not working

### ISSUE THREAD

**Issue by sangatxo** [eXon/videojs-youtube#382] opened 2016-05-03 16:27 UTC
Hi,

I am using video.js v5.9.2 and videojs-youtube v2.0.8. My player plays videos from multiple sources like .mp4 files and Youtube videos as a playlist mode.

It is working fine when all videos are .mp4 files or all videos are Youtube links. The problem is when player change from a youtube video to a .mp4 file. Youtube iframe is not removed of the DOM and it is maintained over the .mp4 video.

I created a jsfiddle with the problem: 
https://jsfiddle.net/8qbgeuuh/9/

It was working fine in old versions with videojs 4. Is it a bug? or am I doing something wrong?

Thanks in advance.

**Comment by gkatsev** [comment] 2016-05-10 21:10
This is a duplicate of #347. It's a bug that should be fixed.

**Closed** 2016-05-11 04:36 UTC
