### ISSUE TITLE
How do I play youtube video on an Ipad or Iphone?

### ISSUE THREAD

**Issue by lvlovestory** [eXon/videojs-youtube#320] opened 2015-11-04 06:22 UTC
It is endlessly rotating circle.
How do I play on Mobile device by default browser?

**Comment by chris-thejok3r** [comment] 2015-11-09 02:43
I have the same problem. I tried to play the first video on my iPhone on this page
http://vjsual.com/de/vjsual-interactive-player-link-und-e-mail-ctas-fuer-ihr-video
The only thing i see is the spinner...

Best regards.
Chris

**Comment by eXon** [comment] 2015-11-09 10:36
I also have the same problem with my iPhone. I have unfortunately very little time to debug this. If you find a fix, please submit a PR!

**Comment by T-L-P** [comment] 2015-11-13 08:35
+1 same problem here. On iPad i have rotating circles on the poster. iPhone plays the video but i dont have a poster.

**Comment by T-L-P** [comment] 2015-11-13 13:45
It has something to do that apple does not allow autoplay of videos. I disabled autoplay but now the poster behaves strange. It is there initially, but disappears as the youtube player loads, it appears again when i press play and disappears when the video starts playing.
Maybe that helps debugging.

**Comment by chris-thejok3r** [comment] 2015-11-17 22:29
It now works for my player. When the player is called on an iOS device i do not set the "controls" option and pass the "ytControls:2" in the data-setup. Then i don't have the nice buttons but the video starts playing.
I also had to leave out an image overlay. I set an "onclick" event to it that called the "player.play()" function but nothing happened. So i don't display it on an iOS device.

**Comment by am-konstantin** [comment] 2015-11-23 09:22
Is there any fix for this? I have the same problem.

**Comment by pazzypunk** [comment] 2015-11-27 18:43
@chris-thejok3r's solution worked for me. Would love to see a resolution in this. :+1:

**Comment by eXon** [comment] 2015-12-14 19:24
I know this sucks. It's my next priority because not working on iOS is kinda really bad.

**Closed** 2015-12-14 22:59 UTC

**Comment by alijaffar** [comment] 2016-01-06 22:10
iPhone video support sucks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Magiweb** [comment] 2016-04-16 18:49
Also still getting issues on iPhones. "Spinning wheel of death" - exactly right.

**Comment by andyrewlee** [comment] 2016-08-29 23:48
It works if i keep tapping around the edges of the spinning wheel of death. after it starts playing successfully once then its fine but it seems to be the problem is in the initial tap. Youtube's red arrow is showing on the initial tap as well I wonder if that has something to do with it.

**Comment by andyrewlee** [comment] 2016-08-29 23:50
oh it works as long as i don't directly tap on the play button but on the edges
