### ISSUE TITLE
Player can't handle a playlist of both mp4 and youtube video

### ISSUE THREAD

**Issue by br3aking-bad** [eXon/videojs-youtube#380] opened 2016-04-18 18:16 UTC
Hello,

I would like to use videojs-playlist to read mp4 and youtube video, but when the player has youtube tech it can't read mp4 files. Do you have an idea to handle this without creating two player objects ?

**Comment by gkatsev** [comment] 2016-05-10 21:09
This sounds like a duplicate of #347.

**Closed** 2016-05-11 04:36 UTC
